image: ubuntu:rolling

before_script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install -y tzdata
    - ln -fs /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime
    - dpkg-reconfigure --frontend noninteractive tzdata
    - apt-get install r-base -y
    - Rscript -e 'install.packages("car")'
    - Rscript -e 'install.packages("pwr")'
    - Rscript -e 'install.packages("BSDA")'
build:
    stage: build
    script:
        - find . -type f -name "*.r" -exec Rscript {} \;