image: r-base:latest

before_script:
    - Rscript -e 'install.packages("car")'
    - Rscript -e 'install.packages("pwr")'
    - Rscript -e 'install.packages("BSDA")'
build:
    stage: build
    script:
        - cd "R"
        - find . -type f -name "*.r" -exec Rscript {} \;